version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trackivity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/trackivity
      REDIS_URL: redis://redis:6379
      PORT: 3000
      SESSION_SECRET: your-secret-key-change-in-production
      SESSION_MAX_AGE: 2592000
      BCRYPT_COST: 12
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
      - ./backend/Cargo.toml:/app/Cargo.toml
      - ./backend/Cargo.lock:/app/Cargo.lock
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: